### ISSUE TITLE
Tosca serialization into yaml

### ISSUE THREAD

**Issue by zatsepinvl** [alien4cloud/alien4cloud#104]
Hi all
I try to serialize tosca from in-memory objects, but can't find any way to do it.
There is ToscaParser inside client4cloud-tosca module, which is used to read tosca, but what about to write tosca? Is some convenient tool to do that with the minimal differences between input and output yaml files: keeping comments, lines formatting and so on?

**Comment by lucboutier** [comment]
Hi Vladimir,

Right now we have a tosca serialiser (alien4cloud/alien4cloud-core/src/main/java/org/alien4cloud/tosca/exporter/ArchiveExportService.java) based on velocity which is part of the alien4cloud-core module as it has a dependency on the application service. We indeed override the archive description with the one from the application in our main module.

I believe that such relation could/should be removed, overrides (description right now) given as a parameter and the exporter moved to the tosca module.

Note that right now we don't parse comments and they will not be kept, as line numbers. Our exporter also right now adds a workflow section that is not 100% compliant with the 1.1 spec. We have planned improvements around this to not export the workflow section when a workflow is exactly matching normative workflow and to get in line with the 1.1 spec.

HTH,

Luc

**Comment by zatsepinvl** [comment]
Thanks.
