### ISSUE TITLE
alien4cloud saml configaration

### ISSUE THREAD

**Issue by LahariGuntha** [alien4cloud/alien4cloud#119]
I am trying to secure my Alien4cloud with Keycloak IDP.I followed official documentation regarding saml integration of Alien4cloud.

link:https://alien4cloud.github.io/#/documentation/1.4.0/admin_guide/saml.html

After following the steps mentioned in the document my Alien4cloud is not redirecting to my IDP login page.Are there any extra configarations to be done??

**Comment by igorng** [comment]
Hello @LahariGuntha 
Thanks you for showing interest and looking into Alien4Cloud.
Please note that as stated in the doc link you provided, **SAML integration** is a **premium feature**. I assume you are working with the Community edition. 

Please kindly contact our team for more informations about the premium edition, by emailing at: **sebastien.bergougnoux@atos.net**

Regards,
Igor
