### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by jwlai** [alien4cloud/alien4cloud#123]
I'm using the curl + script command but am unable to see it running. I get errors and it runs into Error when calling <alien4cloud.dao.ESGenericIdDAO> <findById> I believe it is something to do with elasticsearch. Any help? I have the default configuration files found in 

https://github.com/alien4cloud/alien4cloud/blob/master/alien4cloud-rest-api/src/main/resources/alien4cloud-config.yml
https://github.com/alien4cloud/alien4cloud/blob/master/alien4cloud-ui/src/main/resources/elasticsearch.yml

[alien4cloud.log](https://github.com/alien4cloud/alien4cloud/files/1839255/alien4cloud.log)

**Comment by OresteVisari** [comment]
Hi jwlai,

We actually prepare the next major release of Alien. Some plugins will be deprecated, like the Puccini plugin. So, for the moment, the easy way to try Alien is to download the last version and launch the standalone version like any other Java process.

If you never used Alien before, you can try our [lastest Sprint Milestone](http://fastconnect.org/maven/service/local/artifact/maven/redirect?r=opensource&g=alien4cloud&a=alien4cloud-dist&v=2.0.0-RC2&p=tar.gz&c=dist). 

Finally, if you need more help, you can join the team present on this [Slack](https://alien4cloud-public.slack.com).

**Comment by jwlai** [comment]
How can I join the slack?

**Comment by OresteVisari** [comment]
Did you recived the invitation by mail ?

**Comment by jwlai** [comment]
Hi Oreste, 

I didn't get an invitation. Can you send it again?
