### ISSUE TITLE
Unable to edit service template description and template author in topology modeller archive tree page

### ISSUE THREAD

**Issue by ekowsal** [alien4cloud/alien4cloud#125]
Hi,

I have created new archive from manage archive page, then updated template_author and service template description and saved it.  If I go back to some other page for ex browse topology and coming back  to same topology modeller, the updated value reset to older value. 

tosca_definitions_version: tosca_simple_yaml_1_0
metadata:
  template_name: test
  template_version: 0.1.0-SNAPSHOT
  **template_author**: admin

**description**: "Enclosing archive for topology test"

If it's issue in a4c, I would like to fix this issue and contribute to a4c.  In case  it's expected behaviour, please share the reason behind it.

Thanks,
Kowsalya

**Comment by OresteVisari** [comment]
Hi,

No reason behind this choose, you can make a PR with this changes.
The [AbstractUpdateFileProcessor](https://github.com/alien4cloud/alien4cloud/blob/develop/alien4cloud-core/src/main/java/org/alien4cloud/tosca/editor/processors/AbstractUpdateFileProcessor.java) should be a great entry point for this.

Regards,

**Comment by ekowsal** [comment]
Hi,

When I update description of topology template, the following things are happening.

1.  The updated description is reflected in temporary file in ${alien.home}/tmp//

2. Then updated topology file is parsed and description value set it in ArchiveRoot.Csar.description field

**// the operation updates the topology file, we have to parse it and override the topology data out of it.
                    editorTopologyUploadService.processTopology(artifactRepository.resolveFile(artifactFileId),
                            topology.getWorkspace());**

3. EditorTopologyUploadService.java is updating only topology in EditionContextManager. It supposed to update CSAR in EditionContextManager to reflect updated description value in topology. 

4. Adding the below line in processTopologyParseResult.EditorTopologyUploadService resolves the problem.

EditionContextManager.get().getCsar().setDescription(parsingResult.getResult().getArchive().getDescription());

Please share your thoughts.

**Comment by OresteVisari** [comment]
Hi,

I think you should be able to make a [Pull Request](https://help.github.com/articles/creating-a-pull-request/). That will be more easy to discuss about code.

**Comment by ekowsal** [comment]
Hi,

I gave [pull request for this issue]( https://github.com/alien4cloud/alien4cloud/pull/133). Could you please review it.
