### ISSUE TITLE
Deployment of Alien4cloud

### ISSUE THREAD

**Issue by VincentRavera** [alien4cloud/alien4cloud#127]
Hi,
I made a [docker image of Alien4cloud](https://github.com/VincentRavera/Alien4cloud-Docker), but i think i missed something in the installation.
I can't download the git samples as suggested in the [wiki examples](https://alien4cloud.github.io/#/documentation/1.4.0/getting_started/new_getting_started.html).

Would you mind either, forking my project and correct it, or making your own official image ? 

Thanks,

Vincent

**Comment by OresteVisari** [comment]
Hi,

I launch your Doccker and I'm able to pull the sample from Github.
If you want, share a screen of our "Git location" modal and a log file with the errors.
For information, we planne a 1.4.3.3 for the next week.

Regards,
Philippe

**Comment by VincentRavera** [comment]
Okay here is the screenshot of the Error:
![2018-04-06-173528_1920x1080_scrot](https://user-images.githubusercontent.com/20124583/38430378-6167a32c-39c1-11e8-823e-8e0ac809213b.png)

In the container at 
```Shell
cd /root/alien4cloud-getstarted/alien4cloud/runtime/upload/git/35ce8eae-e2fc-4487-82b9-8e8b6954aef6
```
I have:
![2018-04-06-174128_1920x1080_scrot](https://user-images.githubusercontent.com/20124583/38430537-d05f36a0-39c1-11e8-81c8-0f2d28a96507.png)
So it seems to have pulled the repository correctly.
But the components don't show up in the component list.

> For information, we plan a 1.4.3.3 for the next week.

Okay I will update the install next week, but i'm surprised you didn't get this error.

**Comment by VincentRavera** [comment]
After few tests i discovered that i need to un-check the box.
`Save the repository locally.`
