### ISSUE TITLE
Deployment Ignore artifact's "file" location when "type" of repo is  "a4c_ignore"

### ISSUE THREAD

**Issue by asalic** [alien4cloud/alien4cloud#139]
Alien4Cloud tries to resolve an artifact using its file URI. When a4c starts up there's a method to ignore the artifact using a repository with the type "a4c_ignore" (https://github.com/alien4cloud/alien4cloud/blob/b71c1a69e3b4b84cf2a89335c1ef9eb2c4277463/alien4cloud-core/src/main/java/alien4cloud/repository/services/RepositoryService.java#L111). 

Unfortunately, when one wishes to deploy an infrastructure,  null is returned for the same type (https://github.com/alien4cloud/alien4cloud/blob/b71c1a69e3b4b84cf2a89335c1ef9eb2c4277463/alien4cloud-core/src/main/java/alien4cloud/repository/services/RepositoryService.java#L85).

Is it possible to "mainstream" that ignore approach so we could use it each time we do not want to resolve artifacts at the A4C side? I mean, for instance, we use the "file" field to store an ansible role that is executed when the infrastructure is being deployed. In this case, we can skip downloading artifacts at A4C side each time we deploy something. 

If there's a way to do that  already, I would really appreciate your input. Thanks!

**Comment by xdegenne** [comment]
This has been fixed in the 2.1.0-SM5 released.
Which version of a4c are you currently use ?

**Comment by asalic** [comment]
Okay, I'm using 2.0.0. I'm closing this issue then.
