### ISSUE TITLE
Regarding A4C Archive SNAPSHOT version

### ISSUE THREAD

**Issue by mohanjay** [alien4cloud/alien4cloud#142]
Hi A4CTeam,
                      I could see A4C is creating template version and archive as SNAPSHOT version bu default and from A4C doc, as long as archive is a SNAPSHOT archive i can re-upload it as much as i like and update further. It means SNAPSNOT version is work in progress version and not the completed version.

So How we can conclude on completion of topology archive in A4C. I mean is there any place it could converted to freezed version like 0.1.0. instead of 0.1.0-SNAPSHOT

Also As per TOSCA Spec,  below is the version syntex
<major_version>.<minor_version>[.<fix_version>[.<qualifier>[-<build_version] ] ]
For example 

3.1.0.beta or 3.1.0.SNAPSHOT

but A4C has

 0.1.0-SNAPSHOT

It has -SNAPSHOT instead of .SNAPSHOT. 

Could you please clarify this?

**Comment by mohanjay** [comment]
Hi @EdgarLGB ,
                           Could you please tell me where i can rename the topology archive in A4C Application? Or I need to download the archive and rename it in filesystem.

**Comment by EdgarLGB** [comment]
Here is the [doc](https://alien4cloud.github.io/#/documentation/2.0.0/user_guide/application_versions.html) for updating the version of topology in the application.
