### ISSUE TITLE
2 IO Resources not closed when creating application from template

### ISSUE THREAD

**Issue by stebenoist** [alien4cloud/alien4cloud#156]
When app is created from template, 2 resources are opened and not closed, even when app is removed.

 $ lsof -c java|grep expanded
java    20514 alien  155r      DIR              253,1     4096  2752515 /home/alien/work/runtime/alien4cloud-premium/runtime/csar/Templatetest/0.1.0-SNAPSHOT/expanded
java    20514 alien  245r      DIR              253,1     4096  2752515 /home/alien/work/runtime/alien4cloud-premium/runtime/csar/Templatetest/0.1.0-SNAPSHOT/expanded

**Comment by SebastienLaurent** [comment]
Fix on develop (ALIEN-2961)
