### ISSUE TITLE
Cannot contact alien4cloud

### ISSUE THREAD

**Issue by trihoangvo** [alien4cloud/alien4cloud#174]
Hi,

I have question for premium version but the only contact person on the web site is unreachable sebastien.bergougnoux@atos.net

`The response from the remote server was:
550 Denied by policy. User Unknown.`

I do not know if this project still active or not. And I do not know where else to ask.
This is too bad

**Comment by EdgarLGB** [comment]
Hi @trihoangvo , if you have any public question, please feel free to state it here. Otherwise, you have to wait until someone has updated the contact email.

**Comment by trihoangvo** [comment]
Hi @EdgarLGB

i see this guy asked the same question 6 months ago. It means no contacts updated since 6 months. How could it be possible? Is the project still alive?
https://github.com/alien4cloud/alien4cloud.github.io/issues/72

I am a Cloud architect from a public Cloud provider and looking for a contact person from the project. Can you please write me his or her address?

Thank you

**Comment by trihoangvo** [comment]
Tri.Vo-Hoang@telekom.de
