### ISSUE TITLE
Unable to stop a Cloud because an application is stuck 

### ISSUE THREAD

**Issue by grozeille** [alien4cloud/alien4cloud#28]
Scenario:
I created a Cloud AWS
I activated it
I deployed an application on it
=> it failed to deploy, the UI of alien is stuck with the deployment in progress

Then I wanted to change some properties of the Cloud AWS, so I wanted to disable it
=> It's not possible because an application is deployed on it

So I clicked the button "stop" on the application
=> It's stuck with "Undeployment in progress". I'm not able to force to undeploy and deactivate the Cloud

![capture d ecran 2014-11-13 a 10 22 58](https://cloud.githubusercontent.com/assets/129151/5025960/12c3e858-6b1f-11e4-836c-d0640bd0a377.PNG)

**Comment by lucboutier** [comment]
Many things have changed since this version and this issue has not been reproduced on latest versions.
