### ISSUE TITLE
Visual improvement: name of properties too short

### ISSUE THREAD

**Issue by grozeille** [alien4cloud/alien4cloud#30]
![capture d ecran 2014-11-13 a 16 27 54](https://cloud.githubusercontent.com/assets/129151/5030724/3cd120ce-6b52-11e4-8165-ab5790d59961.PNG)

The name of the property is too short (truncated) even if we have a lot of space on the right (for the checkbox)
Also: it will be nice to be able to increase the size of the panel (with a splitter)

**Comment by lucboutier** [comment]
This has been fixed a long time ago actually.
