### ISSUE TITLE
Still able to deploy despite unrespected min_length constraint

### ISSUE THREAD

**Issue by louisvandiere** [alien4cloud/alien4cloud#33]
I fixed a min_length constraint on a string properties, and I found out that I am still able to deploy even if I dont respect the constraint.

Constraint example:
![constraint](https://cloud.githubusercontent.com/assets/9881297/5140804/c15c8078-716e-11e4-9758-61d922f0e4be.jpg)

In the UI:
![constraint_ui](https://cloud.githubusercontent.com/assets/9881297/5140810/cd7b5f0a-716e-11e4-870b-2cc050f75037.png)

The deployment:
![constraint_ui_deploy](https://cloud.githubusercontent.com/assets/9881297/5140812/d63c6774-716e-11e4-96f5-25e2eac9a133.png)

**Comment by PierreLemordant** [comment]
Hi,

This has been fixed, properties are now required by default.
(It means recipes where properties are optional but where it is not specified have to be modified to explicitly indicate the property is optional)

Regards
