### ISSUE TITLE
Why "save" in Cloud configuration?

### ISSUE THREAD

**Issue by grozeille** [alien4cloud/alien4cloud#41]
There's no "save" action in Alien4Cloud for other screens, except the cloud configuration screen.
Too bad: the button is not visible in a "standard laptop screen" (with a lot of useless whitespace)

And because the other screens don't have any save button, I was not looking for it.
![save](https://cloud.githubusercontent.com/assets/129151/5233918/be613a64-77a7-11e4-9d4a-b3e7fde606d9.PNG)

Why not putting this button on top ?

**Comment by OresteVisari** [comment]
Fixed in SM24.
