### ISSUE TITLE
Unable to top a Cloud even if not application are on it

### ISSUE THREAD

**Issue by grozeille** [alien4cloud/alien4cloud#42]
I tried to deploy an application on the cloud AWS.
It fails because there was a wrong configuration about the block-storage.

So I change the configuration, and tried to stop/start the cloud to use these new settings.
But Alien says that the cloud is used (and that's not true)
![cloudused](https://cloud.githubusercontent.com/assets/129151/5233930/a81451dc-77a8-11e4-975e-4e10af6a6a32.PNG)

**Comment by PierreLemordant** [comment]
Hi,

The problem has been fixed in version 1.0.0M3
Can this ticket be closed ?

Regards
