### ISSUE TITLE
Compute name linux rule

### ISSUE THREAD

**Issue by maniacojazz** [alien4cloud/alien4cloud#44]
The name field allows the underscore ('_') character. But Linux does not allow this character. 
Then, when linux and most of the systems allows the '-' character, Alien does not.

![tiret](https://cloud.githubusercontent.com/assets/3921433/5281005/ceaca1fc-7af8-11e4-9a01-a94fa682c682.PNG)

**Comment by OresteVisari** [comment]
Fixed in SM25.
