### ISSUE TITLE
Default value of Properties still visible in the Topology after removing it

### ISSUE THREAD

**Issue by ViktorOdin** [alien4cloud/alien4cloud#49]
When I remove the default value of a properties in the topology of an application, change page and comeback to this topology, I can see the value of this properties is reset to default. And yet its value is properly set to null in deployement.

I think the topology should not show the default value of properties that have been intentionally deleted.

**Comment by lucboutier** [comment]
Default value is the value that is taken in account by TOSCA orchestrator when no value is provided so that sounds like a correct behaviour. We don't plan to do anything on this subject.
