### ISSUE TITLE
Allow to update a Cloud Image definition

### ISSUE THREAD

**Issue by loicalbertin** [alien4cloud/alien4cloud#50]
Hi aliens,

It would be great if you can allow edition of a Cloud Image's properties after it's creation.
Currently the only way to do it is to delete the image and recreate it.

Thanks & regards,
Loïc

**Comment by PierreLemordant** [comment]
Hi,

This has been added in latest version :
"A cloud image is now editable.
When you display the cloud image details view, you are not yet in edit mode (you can not change the name nor the image). You must click the 'edit' button to switch to edit mode. Then a check is done : if the image is associated to more than 1 cloud, you can only change the ram, cpu and disk space."

Reagrds,

Pierre

**Comment by PierreLemordant** [comment]
A cloud image is now editable.
When you display the cloud image details view, you are not yet in edit mode (you can not change the name nor the image). You must click the 'edit' button to switch to edit mode. Then a check is done : if the image is associated to more than 1 cloud, you can only change the ram, cpu and disk space.
A constraint onto version property format had also been added (GITHUB #51)
