### ISSUE TITLE
Add a format check for the version field of a Cloud Image

### ISSUE THREAD

**Issue by loicalbertin** [alien4cloud/alien4cloud#51]
Hi,

Currently we can write anything in the version field of a Cloud Image definition.
But it seems that when switching to the  deployment view of an application, Alien expect the version to match the following scheme \d+(?:\.\d+)*(?:[\.-]\p{Alnum}+)*  
It would be great if you can check it when defining the image, specially if we can't update the image definition afterwards (see the issue #50).

Thanks & regards,
Loïc

**Comment by lucboutier** [comment]
This is an old issue that is not relevant anymore since 1.1 versions.
