### ISSUE TITLE
Components not visible in Firefox (even in application topology)

### ISSUE THREAD

**Issue by maniacojazz** [alien4cloud/alien4cloud#52]
version : SM18

The component list is not visible on the Firefox browser ; ok on Chrome browser.
I have the same problem when I refresh the cache (ctrl-F5).

![image](https://cloud.githubusercontent.com/assets/3921433/5677593/fed456ec-97e8-11e4-860c-488e79ceaf68.png)

**Comment by maniacojazz** [comment]
OS = Windows 7
FF = 34.0.5

It is an update from 1.0.0-M3 to 1.0.0-SM18, so we destroy the ".alien" repository, restart alien 1.0.0-SM18 (standalone version).

**Comment by PierreLemordant** [comment]
Hi,
Does the version 1.0.0-SM18 fix your problem ? 
We didn't reproduce your problem with window 7 and ff 34.0.5

Regards.

**Comment by maniacojazz** [comment]
This seems to be resolved after reinstall of alien.
