### ISSUE TITLE
Import and Export of a yaml topology into an application

### ISSUE THREAD

**Issue by maniacojazz** [alien4cloud/alien4cloud#53]
In our continuous integration test environment, we would like to have the possibility to import a yaml topology into a specific application, instead of having as many applications as test environment.

This yaml topology should be exported from an existing application of Alien UI.

These 2 functionalities should be available from Alien UI and REST API.

Thanks,

Thomas.

**Comment by lucboutier** [comment]
Topology export is included in a4c 1.3.x versions.
