### ISSUE TITLE
How to build the project

### ISSUE THREAD

**Issue by andreaturli** [alien4cloud/alien4cloud#56]
I'm trying to build alien4cloud/alien4cloud but I have some problems with maven repositories

[ERROR] Failed to execute goal on project alien4cloud-core: Could not resolve dependencies for project alien4cloud:alien4cloud-core:jar:1.0.0-SM24: Failed to collect dependencies at alien4cloud:alien4cloud-security:jar:1.0.0-SM24: Failed to read artifact descriptor for alien4cloud:alien4cloud-security:jar:1.0.0-SM24: Could not transfer artifact alien4cloud:alien4cloud-security:pom:1.0.0-SM24 from/to repo.opensource.fastconnect.org (http://fastconnect.org/maven/content/repositories/opensource): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

Could you improve the README to solve this issue?

**Comment by lucboutier** [comment]
Hi,

Can you try to run 
mvn clean install -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true

If that works for you I'll update the readme with this info.

If there is any other information to add please feel welcome to give us your input.

**Comment by andreaturli** [comment]
Hi @lucboutier,

looks much better now! 

Thanks
Actually I was still exploring your nice project! I'm particularly interested on the TOSCA support you have. Any plan to release that as independent sub-project?

**Comment by lucboutier** [comment]
Hi @andreaturli,

Let's follow this topic on #57.

Luc

**Comment by andreaturli** [comment]
Great @lucboutier !

Andrea
