### ISSUE TITLE
refactor TOSCA parser to a separate maven sub-project

### ISSUE THREAD

**Issue by ahgittin** [alien4cloud/alien4cloud#57]
nice job on the tosca parser!

it would be really useful for other projects to be able to consume this independently of the rest of alien4cloud.  (i know of a couple which would like to do this, apache brooklyn and seaclouds.  there's interest in a deeper integration too but this looks like a clean first cut.)

i wanted to check if there would be any objections to this?  /cc @lucboutier 

(btw i'm not suggesting you do it!  some of the people on the projects above could pick this up.)

best
alex

**Comment by lucboutier** [comment]
Hi @ahgittin, @andreaturli,

From high level we are OpenSource licensed under Apache 2 so you can take some code of course. I suggest we discuss that in detail on may 26/27th when we meet in London.

Luc

**Comment by andreaturli** [comment]
Great @lucboutier, sounds great! 

I think we will simply try to use https://github.com/alien4cloud/alien4cloud/tree/master/alien4cloud-core even if it will transitively Spring and other dependencies that may be we don't need, but it is more than enough to start a deeper integration. Thanks
