### ISSUE TITLE
Extended TOSCA types

### ISSUE THREAD

**Issue by dinitto** [alien4cloud/alien4cloud#58]
Dear all

I'm from the SeaClouds team as Alex. We are curious to know if your parser for TOSCA is supporting also the extended TOSCA types.
Many thanks for your answers
Cheers
Elisabetta

**Comment by lucboutier** [comment]
Hi Elisabetta,

Sorry for the late answer but actually I'm not sure what you exactly mean by 'extended TOSCA types'... If you mean topology substitution we don't support that yet but plan to do it in the next versions of a4c. If you mean just types that can be extended (derived_from) other types then of course we do support that...

HTH,

Luc

**Comment by marcoriol** [comment]
Thank you very much Luc, we indeed meant "types that can be extended (derived_from) other types". So it's great that they are supported :)
