### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by buccarel** [alien4cloud/alien4cloud#59]
Hello,

I am Mattia Buccarella, from the SeaClouds development.

I donwloaded the source code of A4C and I am willing to use its parser to read TOSCA files. When I try to instantiate the parser, more precisely when I call the initialize() method, all the private fields annotated with @Resource just stay set to null. Do you know why?

I cloned the git repository then I used maven to build it, without touching anything.

**Comment by ahgittin** [comment]
Hi @buccarel -- suggest you familiarise yourself with Spring. This is not an A4C issue.
