### ISSUE TITLE
Errors with urls

### ISSUE THREAD

**Issue by grozeille** [alien4cloud/alien4cloud#6]
I deployed Alien4Cloud in a standard Tomcat with the url "http://localhost:8080/alien/".
If I'm missing the last "/", the WebSite is not able to load:
![pastedgraphic-13](https://cloud.githubusercontent.com/assets/129151/4514828/13729f30-4b92-11e4-811c-15a8e496c98e.jpg)
When the session has expired, I'm not redirected to the login screen "http://localhost:8080/alien/", but the Tomcat screen "http://localhost:8080/":
![pastedgraphic-14](https://cloud.githubusercontent.com/assets/129151/4514829/27b268ea-4b92-11e4-9459-ba048d694710.jpg)

**Comment by lucboutier** [comment]
Deployment in tomcat is not supported.

People should use the packaged version.
