### ISSUE TITLE
TOSCA parser serialization

### ISSUE THREAD

**Issue by szenzaro** [alien4cloud/alien4cloud#64]
Hi, 
is it possible to serialize to TOSCA yaml using the parser?

**Comment by YoannLP** [comment]
Hi, 
What is your purpose?

**Comment by szenzaro** [comment]
I am using the results of https://github.com/alien4cloud/alien4cloud/issues/57 and was checking if the A4C TOSCA parser is able to serialize to TOSCA

**Comment by lucboutier** [comment]
We do serialize TOSCA but not with the same utility. We use a simpler implementation based on velocity.

**Comment by szenzaro** [comment]
Ok thank you!

**Comment by lucboutier** [comment]
See
https://github.com/alien4cloud/alien4cloud/tree/develop/alien4cloud-core/src/main/java/alien4cloud/tosca/serializer

Not sure if we serialize everything right now or just topologies (that is our use-case currently in Alien)

**Comment by szenzaro** [comment]
Thanks!
