### ISSUE TITLE
A4C TOSCA parser policies

### ISSUE THREAD

**Issue by szenzaro** [alien4cloud/alien4cloud#66]
Hi, 
I have seen that the a4c TOSCA parser handles policies via custom classes.
How one can define a policy that the parse is able to parse?

**Comment by lucboutier** [comment]
This is currently not supported in our parser.

**Comment by lucboutier** [comment]
Actually Policies are still not well defined in TOSCA (that's currently being discussed). We are waiting for the TC on this one.

**Comment by ahgittin** [comment]
temporary workaround available in #70

**Comment by lucboutier** [comment]
Workaround merged in develop.
