### ISSUE TITLE
Using list in property types

### ISSUE THREAD

**Issue by kiuby88** [alien4cloud/alien4cloud#73]
Hi

I'd like to use the list type for a NodeType property. However, when I use this type, the parser fails saying: `Type list must define entry schema`.
I took a look to the source code and I found a `List` type in `ToscaTypes` class but I did not found any use example (test, yaml, etc...)
Do you know something about this?

**Comment by lucboutier** [comment]
As specified in TOSCA spec you must define an entry schema....

You can look at unit tests data:
https://github.com/alien4cloud/alien4cloud/blob/develop/alien4cloud-core/src/test/resources/tosca/SimpleProfile_wd03/parsing/tosca-data-types.yml

**Comment by kiuby88** [comment]
Thx
