### ISSUE TITLE
Components upload error

### ISSUE THREAD

**Issue by lewang0418** [alien4cloud/alien4cloud#75]
Hi,

I am trying A4C with this alien4cloud-ui-1.0.0-standalone.war. I fail to upload "normative-types" and error message I get is " Alien 4 Cloud currently supports a single definition file within an archive.". The normative-types is downloaded from here https://github.com/alien4cloud/tosca-normative-types/archive/master.zip
[Could you point out where I am wrong? The guide I am following is this http://alien4cloud.github.io/index.html#/documentation/1.0.0/getting_started/getting_started.html

Thx,
Le

**Comment by OresteVisari** [comment]
Hi,

Make sure you have the "normative-types.yml" file at the top level of your zip archive.

Regards,
Philippe

**Comment by lewang0418** [comment]
Right, thanks for the tips.

BR,
Le
